export enum Category {  // https://www.typescriptlang.org/docs/handbook/enums.html;
  Accessories = 'ACCESSORIES',
  Automotive = 'AUTOMOTIVE',
  Beauty = 'BEAUTY',
  Clothing = 'CLOTHING',
  Books = 'BOOKS',
  Electronics = 'ELECTRONICS',
  Entertainment = 'ENTERTAINMENT',
  Fashion = 'FASHION',
  Handmade = 'HANDMADE',
  Household = 'HOUSEHOLD',
  Lifestyle = 'LIFESTYLE',
  Outdoors = 'OUTDOORS',
  Photo = 'PHOTO',
  Software = 'SOFTWARE',
  Sports = 'SPORTS',
  Tools = 'TOOLS',
  Video = 'VIDEO',
  Watches = 'WATCHES',
}
